[cluster]

[[cluster.group]]
addr_list = [":8081", ":8082", ":8083"]

[[cluster.nodes]]
addr_list = [":8084", ":8085", ":8086"]

[[cluster.nodes]]
addr_list = [":8087", ":8088", ":8089"]

[persister]
state = "/tmp/kvraft/state"
snapshot = "/tmp/kvraft/snapshot"
