[cluster]

[[cluster.nodes]]
id = 0
host = "127.0.0.1"
port = ":8080"

[[cluster.nodes]]
id = 1
host = "127.0.0.1"
port = ":8081"

[[cluster.nodes]]
id = 2
host = "127.0.0.1"
port = ":8082"


[persister]
state = "/tmp/kvraft/state"
snapshot = "/tmp/kvraft/snapshot"
